---
title: "Desigualdad Educativa en Chile: Perspectiva sobre el Acceso y Efectos en Pueblos Originarios"
format: html
editor: visual
bibliography: Trabajo.bib
link-citations: true
---

##### Por: José Norambuena

No tiene mucha discusión el hecho de que para el año 2011 el movimiento estudiantil chileno fue el movimiento social con mayor convocatoria y visible desde el retorno a la democracia [@sanchezMovimientoEstudiantilChile2012]. Por otro lado, fueron estos estudiantes los que instalan las demandas como por ejemplo la gratuidad en la educación, el fin al lucro en las instituciones educativas, educación de calidad y fin al endeudamiento, siendo estas las principales, en la agenda de gobierno del entonces presidente Sebastián Piñera mediante masivas convocatorias que llegan a más de 400.000 personas en las calles, paralizando así a gran parte de las universidades del país, al igual que a más de cien liceos que fueron sitiados por sus mismos estudiantes [@poncelaraRedesConfianzaOnline2016]. También, influye en gran medida la ampliación de la clase media dado un mayor acceso a la educación superior [@fleetMovimientoEstudiantilTransformaciones2011].

Creo que es importante mencionar el contexto en el cual este movimiento altamente visible ve su emergencia, puesto que como dije anteriormente Sebastián Piñera era quien se sentaba en el sillón presidencial, lo anecdótico de este suceso es que Piñera en ese momento fue el primer presidente de \"derecha\" electo democráticamente para gobernar en país postdictadura. Además, el entonces ministro de educación era Joaquín Lavín, era conocido como el eterno candidato de la derecha del partido Unión Demócrata Independiente (UDI), opus dei y también vinculado con sociedades anónimas a la Universidad del Desarrollo de carácter privado. 

Hay investigadores, como Ouviña (2012) que señalan que estos actores involucrados en manifestaciones como la del 2006 o la del 2011 pertenecen a una generación que perdió el miedo a protestar puesto que no nacieron en dictadura.
